/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FullscreenRouteImport } from './routes/_fullscreen'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as FullscreenToolsEditorRouteImport } from './routes/_fullscreen.tools.editor'
import { Route as FullscreenEditorProjectIdRouteImport } from './routes/_fullscreen.editor.$projectId'
import { Route as AppToolsVideoStudioRouteImport } from './routes/_app.tools.video-studio'
import { Route as AppToolsStoryDirectorRouteImport } from './routes/_app.tools.story-director'
import { Route as AppToolsReactionVideoRouteImport } from './routes/_app.tools.reaction-video'
import { Route as AppToolsReactionCreatorRouteImport } from './routes/_app.tools.reaction-creator'
import { Route as AppToolsReactionRouteImport } from './routes/_app.tools.reaction'
import { Route as AppToolsModernEditorRouteImport } from './routes/_app.tools.modern-editor'
import { Route as AppToolsLoopCreatorRouteImport } from './routes/_app.tools.loop-creator'
import { Route as AppToolsLiveStreamHistoryRouteImport } from './routes/_app.tools.live-stream-history'
import { Route as AppToolsLiveStreamRouteImport } from './routes/_app.tools.live-stream'
import { Route as AppToolsAiDirectorRouteImport } from './routes/_app.tools.ai-director'
import { Route as AppDashboardTrendingRouteImport } from './routes/_app.dashboard_.trending'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app.dashboard_.settings'
import { Route as AppDashboardPromptsRouteImport } from './routes/_app.dashboard_.prompts'
import { Route as AppDashboardProjectsRouteImport } from './routes/_app.dashboard_.projects'
import { Route as AppDashboardPricingRouteImport } from './routes/_app.dashboard_.pricing'
import { Route as AppDashboardHistoryRouteImport } from './routes/_app.dashboard_.history'
import { Route as AppDashboardExportsRouteImport } from './routes/_app.dashboard_.exports'
import { Route as AppDashboardDownloadsRouteImport } from './routes/_app.dashboard_.downloads'
import { Route as AppDashboardCommunityRouteImport } from './routes/_app.dashboard_.community'
import { Route as AppDashboardAdminRouteImport } from './routes/_app.dashboard_.admin'
import { Route as AppToolsStoryDirectorProjectIdRouteImport } from './routes/_app.tools.story-director_.$projectId'
import { Route as AppDashboardPromptsNewRouteImport } from './routes/_app.dashboard_.prompts_.new'
import { Route as AppDashboardPromptsIdRouteImport } from './routes/_app.dashboard_.prompts_.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FullscreenRoute = FullscreenRouteImport.update({
  id: '/_fullscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const FullscreenToolsEditorRoute = FullscreenToolsEditorRouteImport.update({
  id: '/tools/editor',
  path: '/tools/editor',
  getParentRoute: () => FullscreenRoute,
} as any)
const FullscreenEditorProjectIdRoute =
  FullscreenEditorProjectIdRouteImport.update({
    id: '/editor/$projectId',
    path: '/editor/$projectId',
    getParentRoute: () => FullscreenRoute,
  } as any)
const AppToolsVideoStudioRoute = AppToolsVideoStudioRouteImport.update({
  id: '/tools/video-studio',
  path: '/tools/video-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsStoryDirectorRoute = AppToolsStoryDirectorRouteImport.update({
  id: '/tools/story-director',
  path: '/tools/story-director',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsReactionVideoRoute = AppToolsReactionVideoRouteImport.update({
  id: '/tools/reaction-video',
  path: '/tools/reaction-video',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsReactionCreatorRoute = AppToolsReactionCreatorRouteImport.update({
  id: '/tools/reaction-creator',
  path: '/tools/reaction-creator',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsReactionRoute = AppToolsReactionRouteImport.update({
  id: '/tools/reaction',
  path: '/tools/reaction',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsModernEditorRoute = AppToolsModernEditorRouteImport.update({
  id: '/tools/modern-editor',
  path: '/tools/modern-editor',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsLoopCreatorRoute = AppToolsLoopCreatorRouteImport.update({
  id: '/tools/loop-creator',
  path: '/tools/loop-creator',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsLiveStreamHistoryRoute =
  AppToolsLiveStreamHistoryRouteImport.update({
    id: '/tools/live-stream-history',
    path: '/tools/live-stream-history',
    getParentRoute: () => AppRoute,
  } as any)
const AppToolsLiveStreamRoute = AppToolsLiveStreamRouteImport.update({
  id: '/tools/live-stream',
  path: '/tools/live-stream',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsAiDirectorRoute = AppToolsAiDirectorRouteImport.update({
  id: '/tools/ai-director',
  path: '/tools/ai-director',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardTrendingRoute = AppDashboardTrendingRouteImport.update({
  id: '/dashboard_/trending',
  path: '/dashboard/trending',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/dashboard_/settings',
  path: '/dashboard/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardPromptsRoute = AppDashboardPromptsRouteImport.update({
  id: '/dashboard_/prompts',
  path: '/dashboard/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardProjectsRoute = AppDashboardProjectsRouteImport.update({
  id: '/dashboard_/projects',
  path: '/dashboard/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardPricingRoute = AppDashboardPricingRouteImport.update({
  id: '/dashboard_/pricing',
  path: '/dashboard/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardHistoryRoute = AppDashboardHistoryRouteImport.update({
  id: '/dashboard_/history',
  path: '/dashboard/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardExportsRoute = AppDashboardExportsRouteImport.update({
  id: '/dashboard_/exports',
  path: '/dashboard/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardDownloadsRoute = AppDashboardDownloadsRouteImport.update({
  id: '/dashboard_/downloads',
  path: '/dashboard/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardCommunityRoute = AppDashboardCommunityRouteImport.update({
  id: '/dashboard_/community',
  path: '/dashboard/community',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardAdminRoute = AppDashboardAdminRouteImport.update({
  id: '/dashboard_/admin',
  path: '/dashboard/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsStoryDirectorProjectIdRoute =
  AppToolsStoryDirectorProjectIdRouteImport.update({
    id: '/tools/story-director_/$projectId',
    path: '/tools/story-director/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardPromptsNewRoute = AppDashboardPromptsNewRouteImport.update({
  id: '/dashboard_/prompts_/new',
  path: '/dashboard/prompts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardPromptsIdRoute = AppDashboardPromptsIdRouteImport.update({
  id: '/dashboard_/prompts_/$id',
  path: '/dashboard/prompts/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/admin': typeof AppDashboardAdminRoute
  '/dashboard/community': typeof AppDashboardCommunityRoute
  '/dashboard/downloads': typeof AppDashboardDownloadsRoute
  '/dashboard/exports': typeof AppDashboardExportsRoute
  '/dashboard/history': typeof AppDashboardHistoryRoute
  '/dashboard/pricing': typeof AppDashboardPricingRoute
  '/dashboard/projects': typeof AppDashboardProjectsRoute
  '/dashboard/prompts': typeof AppDashboardPromptsRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/trending': typeof AppDashboardTrendingRoute
  '/tools/ai-director': typeof AppToolsAiDirectorRoute
  '/tools/live-stream': typeof AppToolsLiveStreamRoute
  '/tools/live-stream-history': typeof AppToolsLiveStreamHistoryRoute
  '/tools/loop-creator': typeof AppToolsLoopCreatorRoute
  '/tools/modern-editor': typeof AppToolsModernEditorRoute
  '/tools/reaction': typeof AppToolsReactionRoute
  '/tools/reaction-creator': typeof AppToolsReactionCreatorRoute
  '/tools/reaction-video': typeof AppToolsReactionVideoRoute
  '/tools/story-director': typeof AppToolsStoryDirectorRoute
  '/tools/video-studio': typeof AppToolsVideoStudioRoute
  '/editor/$projectId': typeof FullscreenEditorProjectIdRoute
  '/tools/editor': typeof FullscreenToolsEditorRoute
  '/dashboard/prompts/$id': typeof AppDashboardPromptsIdRoute
  '/dashboard/prompts/new': typeof AppDashboardPromptsNewRoute
  '/tools/story-director/$projectId': typeof AppToolsStoryDirectorProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/admin': typeof AppDashboardAdminRoute
  '/dashboard/community': typeof AppDashboardCommunityRoute
  '/dashboard/downloads': typeof AppDashboardDownloadsRoute
  '/dashboard/exports': typeof AppDashboardExportsRoute
  '/dashboard/history': typeof AppDashboardHistoryRoute
  '/dashboard/pricing': typeof AppDashboardPricingRoute
  '/dashboard/projects': typeof AppDashboardProjectsRoute
  '/dashboard/prompts': typeof AppDashboardPromptsRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/trending': typeof AppDashboardTrendingRoute
  '/tools/ai-director': typeof AppToolsAiDirectorRoute
  '/tools/live-stream': typeof AppToolsLiveStreamRoute
  '/tools/live-stream-history': typeof AppToolsLiveStreamHistoryRoute
  '/tools/loop-creator': typeof AppToolsLoopCreatorRoute
  '/tools/modern-editor': typeof AppToolsModernEditorRoute
  '/tools/reaction': typeof AppToolsReactionRoute
  '/tools/reaction-creator': typeof AppToolsReactionCreatorRoute
  '/tools/reaction-video': typeof AppToolsReactionVideoRoute
  '/tools/story-director': typeof AppToolsStoryDirectorRoute
  '/tools/video-studio': typeof AppToolsVideoStudioRoute
  '/editor/$projectId': typeof FullscreenEditorProjectIdRoute
  '/tools/editor': typeof FullscreenToolsEditorRoute
  '/dashboard/prompts/$id': typeof AppDashboardPromptsIdRoute
  '/dashboard/prompts/new': typeof AppDashboardPromptsNewRoute
  '/tools/story-director/$projectId': typeof AppToolsStoryDirectorProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_fullscreen': typeof FullscreenRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/dashboard_/admin': typeof AppDashboardAdminRoute
  '/_app/dashboard_/community': typeof AppDashboardCommunityRoute
  '/_app/dashboard_/downloads': typeof AppDashboardDownloadsRoute
  '/_app/dashboard_/exports': typeof AppDashboardExportsRoute
  '/_app/dashboard_/history': typeof AppDashboardHistoryRoute
  '/_app/dashboard_/pricing': typeof AppDashboardPricingRoute
  '/_app/dashboard_/projects': typeof AppDashboardProjectsRoute
  '/_app/dashboard_/prompts': typeof AppDashboardPromptsRoute
  '/_app/dashboard_/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard_/trending': typeof AppDashboardTrendingRoute
  '/_app/tools/ai-director': typeof AppToolsAiDirectorRoute
  '/_app/tools/live-stream': typeof AppToolsLiveStreamRoute
  '/_app/tools/live-stream-history': typeof AppToolsLiveStreamHistoryRoute
  '/_app/tools/loop-creator': typeof AppToolsLoopCreatorRoute
  '/_app/tools/modern-editor': typeof AppToolsModernEditorRoute
  '/_app/tools/reaction': typeof AppToolsReactionRoute
  '/_app/tools/reaction-creator': typeof AppToolsReactionCreatorRoute
  '/_app/tools/reaction-video': typeof AppToolsReactionVideoRoute
  '/_app/tools/story-director': typeof AppToolsStoryDirectorRoute
  '/_app/tools/video-studio': typeof AppToolsVideoStudioRoute
  '/_fullscreen/editor/$projectId': typeof FullscreenEditorProjectIdRoute
  '/_fullscreen/tools/editor': typeof FullscreenToolsEditorRoute
  '/_app/dashboard_/prompts_/$id': typeof AppDashboardPromptsIdRoute
  '/_app/dashboard_/prompts_/new': typeof AppDashboardPromptsNewRoute
  '/_app/tools/story-director_/$projectId': typeof AppToolsStoryDirectorProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/community'
    | '/dashboard/downloads'
    | '/dashboard/exports'
    | '/dashboard/history'
    | '/dashboard/pricing'
    | '/dashboard/projects'
    | '/dashboard/prompts'
    | '/dashboard/settings'
    | '/dashboard/trending'
    | '/tools/ai-director'
    | '/tools/live-stream'
    | '/tools/live-stream-history'
    | '/tools/loop-creator'
    | '/tools/modern-editor'
    | '/tools/reaction'
    | '/tools/reaction-creator'
    | '/tools/reaction-video'
    | '/tools/story-director'
    | '/tools/video-studio'
    | '/editor/$projectId'
    | '/tools/editor'
    | '/dashboard/prompts/$id'
    | '/dashboard/prompts/new'
    | '/tools/story-director/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/community'
    | '/dashboard/downloads'
    | '/dashboard/exports'
    | '/dashboard/history'
    | '/dashboard/pricing'
    | '/dashboard/projects'
    | '/dashboard/prompts'
    | '/dashboard/settings'
    | '/dashboard/trending'
    | '/tools/ai-director'
    | '/tools/live-stream'
    | '/tools/live-stream-history'
    | '/tools/loop-creator'
    | '/tools/modern-editor'
    | '/tools/reaction'
    | '/tools/reaction-creator'
    | '/tools/reaction-video'
    | '/tools/story-director'
    | '/tools/video-studio'
    | '/editor/$projectId'
    | '/tools/editor'
    | '/dashboard/prompts/$id'
    | '/dashboard/prompts/new'
    | '/tools/story-director/$projectId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_auth'
    | '/_fullscreen'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/dashboard_/admin'
    | '/_app/dashboard_/community'
    | '/_app/dashboard_/downloads'
    | '/_app/dashboard_/exports'
    | '/_app/dashboard_/history'
    | '/_app/dashboard_/pricing'
    | '/_app/dashboard_/projects'
    | '/_app/dashboard_/prompts'
    | '/_app/dashboard_/settings'
    | '/_app/dashboard_/trending'
    | '/_app/tools/ai-director'
    | '/_app/tools/live-stream'
    | '/_app/tools/live-stream-history'
    | '/_app/tools/loop-creator'
    | '/_app/tools/modern-editor'
    | '/_app/tools/reaction'
    | '/_app/tools/reaction-creator'
    | '/_app/tools/reaction-video'
    | '/_app/tools/story-director'
    | '/_app/tools/video-studio'
    | '/_fullscreen/editor/$projectId'
    | '/_fullscreen/tools/editor'
    | '/_app/dashboard_/prompts_/$id'
    | '/_app/dashboard_/prompts_/new'
    | '/_app/tools/story-director_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  FullscreenRoute: typeof FullscreenRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_fullscreen': {
      id: '/_fullscreen'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FullscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_fullscreen/tools/editor': {
      id: '/_fullscreen/tools/editor'
      path: '/tools/editor'
      fullPath: '/tools/editor'
      preLoaderRoute: typeof FullscreenToolsEditorRouteImport
      parentRoute: typeof FullscreenRoute
    }
    '/_fullscreen/editor/$projectId': {
      id: '/_fullscreen/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof FullscreenEditorProjectIdRouteImport
      parentRoute: typeof FullscreenRoute
    }
    '/_app/tools/video-studio': {
      id: '/_app/tools/video-studio'
      path: '/tools/video-studio'
      fullPath: '/tools/video-studio'
      preLoaderRoute: typeof AppToolsVideoStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/story-director': {
      id: '/_app/tools/story-director'
      path: '/tools/story-director'
      fullPath: '/tools/story-director'
      preLoaderRoute: typeof AppToolsStoryDirectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/reaction-video': {
      id: '/_app/tools/reaction-video'
      path: '/tools/reaction-video'
      fullPath: '/tools/reaction-video'
      preLoaderRoute: typeof AppToolsReactionVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/reaction-creator': {
      id: '/_app/tools/reaction-creator'
      path: '/tools/reaction-creator'
      fullPath: '/tools/reaction-creator'
      preLoaderRoute: typeof AppToolsReactionCreatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/reaction': {
      id: '/_app/tools/reaction'
      path: '/tools/reaction'
      fullPath: '/tools/reaction'
      preLoaderRoute: typeof AppToolsReactionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/modern-editor': {
      id: '/_app/tools/modern-editor'
      path: '/tools/modern-editor'
      fullPath: '/tools/modern-editor'
      preLoaderRoute: typeof AppToolsModernEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/loop-creator': {
      id: '/_app/tools/loop-creator'
      path: '/tools/loop-creator'
      fullPath: '/tools/loop-creator'
      preLoaderRoute: typeof AppToolsLoopCreatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/live-stream-history': {
      id: '/_app/tools/live-stream-history'
      path: '/tools/live-stream-history'
      fullPath: '/tools/live-stream-history'
      preLoaderRoute: typeof AppToolsLiveStreamHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/live-stream': {
      id: '/_app/tools/live-stream'
      path: '/tools/live-stream'
      fullPath: '/tools/live-stream'
      preLoaderRoute: typeof AppToolsLiveStreamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/ai-director': {
      id: '/_app/tools/ai-director'
      path: '/tools/ai-director'
      fullPath: '/tools/ai-director'
      preLoaderRoute: typeof AppToolsAiDirectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/trending': {
      id: '/_app/dashboard_/trending'
      path: '/dashboard/trending'
      fullPath: '/dashboard/trending'
      preLoaderRoute: typeof AppDashboardTrendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/settings': {
      id: '/_app/dashboard_/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/prompts': {
      id: '/_app/dashboard_/prompts'
      path: '/dashboard/prompts'
      fullPath: '/dashboard/prompts'
      preLoaderRoute: typeof AppDashboardPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/projects': {
      id: '/_app/dashboard_/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AppDashboardProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/pricing': {
      id: '/_app/dashboard_/pricing'
      path: '/dashboard/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof AppDashboardPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/history': {
      id: '/_app/dashboard_/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AppDashboardHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/exports': {
      id: '/_app/dashboard_/exports'
      path: '/dashboard/exports'
      fullPath: '/dashboard/exports'
      preLoaderRoute: typeof AppDashboardExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/downloads': {
      id: '/_app/dashboard_/downloads'
      path: '/dashboard/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof AppDashboardDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/community': {
      id: '/_app/dashboard_/community'
      path: '/dashboard/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof AppDashboardCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/admin': {
      id: '/_app/dashboard_/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AppDashboardAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/story-director_/$projectId': {
      id: '/_app/tools/story-director_/$projectId'
      path: '/tools/story-director/$projectId'
      fullPath: '/tools/story-director/$projectId'
      preLoaderRoute: typeof AppToolsStoryDirectorProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/prompts_/new': {
      id: '/_app/dashboard_/prompts_/new'
      path: '/dashboard/prompts/new'
      fullPath: '/dashboard/prompts/new'
      preLoaderRoute: typeof AppDashboardPromptsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard_/prompts_/$id': {
      id: '/_app/dashboard_/prompts_/$id'
      path: '/dashboard/prompts/$id'
      fullPath: '/dashboard/prompts/$id'
      preLoaderRoute: typeof AppDashboardPromptsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDashboardAdminRoute: typeof AppDashboardAdminRoute
  AppDashboardCommunityRoute: typeof AppDashboardCommunityRoute
  AppDashboardDownloadsRoute: typeof AppDashboardDownloadsRoute
  AppDashboardExportsRoute: typeof AppDashboardExportsRoute
  AppDashboardHistoryRoute: typeof AppDashboardHistoryRoute
  AppDashboardPricingRoute: typeof AppDashboardPricingRoute
  AppDashboardProjectsRoute: typeof AppDashboardProjectsRoute
  AppDashboardPromptsRoute: typeof AppDashboardPromptsRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardTrendingRoute: typeof AppDashboardTrendingRoute
  AppToolsAiDirectorRoute: typeof AppToolsAiDirectorRoute
  AppToolsLiveStreamRoute: typeof AppToolsLiveStreamRoute
  AppToolsLiveStreamHistoryRoute: typeof AppToolsLiveStreamHistoryRoute
  AppToolsLoopCreatorRoute: typeof AppToolsLoopCreatorRoute
  AppToolsModernEditorRoute: typeof AppToolsModernEditorRoute
  AppToolsReactionRoute: typeof AppToolsReactionRoute
  AppToolsReactionCreatorRoute: typeof AppToolsReactionCreatorRoute
  AppToolsReactionVideoRoute: typeof AppToolsReactionVideoRoute
  AppToolsStoryDirectorRoute: typeof AppToolsStoryDirectorRoute
  AppToolsVideoStudioRoute: typeof AppToolsVideoStudioRoute
  AppDashboardPromptsIdRoute: typeof AppDashboardPromptsIdRoute
  AppDashboardPromptsNewRoute: typeof AppDashboardPromptsNewRoute
  AppToolsStoryDirectorProjectIdRoute: typeof AppToolsStoryDirectorProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDashboardAdminRoute: AppDashboardAdminRoute,
  AppDashboardCommunityRoute: AppDashboardCommunityRoute,
  AppDashboardDownloadsRoute: AppDashboardDownloadsRoute,
  AppDashboardExportsRoute: AppDashboardExportsRoute,
  AppDashboardHistoryRoute: AppDashboardHistoryRoute,
  AppDashboardPricingRoute: AppDashboardPricingRoute,
  AppDashboardProjectsRoute: AppDashboardProjectsRoute,
  AppDashboardPromptsRoute: AppDashboardPromptsRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardTrendingRoute: AppDashboardTrendingRoute,
  AppToolsAiDirectorRoute: AppToolsAiDirectorRoute,
  AppToolsLiveStreamRoute: AppToolsLiveStreamRoute,
  AppToolsLiveStreamHistoryRoute: AppToolsLiveStreamHistoryRoute,
  AppToolsLoopCreatorRoute: AppToolsLoopCreatorRoute,
  AppToolsModernEditorRoute: AppToolsModernEditorRoute,
  AppToolsReactionRoute: AppToolsReactionRoute,
  AppToolsReactionCreatorRoute: AppToolsReactionCreatorRoute,
  AppToolsReactionVideoRoute: AppToolsReactionVideoRoute,
  AppToolsStoryDirectorRoute: AppToolsStoryDirectorRoute,
  AppToolsVideoStudioRoute: AppToolsVideoStudioRoute,
  AppDashboardPromptsIdRoute: AppDashboardPromptsIdRoute,
  AppDashboardPromptsNewRoute: AppDashboardPromptsNewRoute,
  AppToolsStoryDirectorProjectIdRoute: AppToolsStoryDirectorProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface FullscreenRouteChildren {
  FullscreenEditorProjectIdRoute: typeof FullscreenEditorProjectIdRoute
  FullscreenToolsEditorRoute: typeof FullscreenToolsEditorRoute
}

const FullscreenRouteChildren: FullscreenRouteChildren = {
  FullscreenEditorProjectIdRoute: FullscreenEditorProjectIdRoute,
  FullscreenToolsEditorRoute: FullscreenToolsEditorRoute,
}

const FullscreenRouteWithChildren = FullscreenRoute._addFileChildren(
  FullscreenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  FullscreenRoute: FullscreenRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
