import type { StudioAsset, StudioTextLayerData, StudioTextPreview } from './video-studio.schemas';

const originalLicense: StudioAsset['license'] = {
  name: 'Vibe Creator Original',
  sourceUrl: null,
  attributionRequired: false,
  commercialUse: true,
};

type TextAssetInput = Pick<
  StudioAsset,
  'id' | 'title' | 'description' | 'category' | 'tags' | 'sortOrder'
> & {
  text: string;
  durationMs: number;
  x: number;
  y: number;
  width: number;
  height: number;
  data: StudioTextLayerData;
  preview: StudioTextPreview;
};

function textAsset(input: TextAssetInput): StudioAsset {
  return {
    id: input.id,
    kind: 'text',
    title: input.title,
    description: input.description,
    category: input.category,
    tags: input.tags,
    thumbnailUrl: null,
    previewUrl: null,
    payload: {
      kind: 'text-layer',
      text: input.text,
      durationMs: input.durationMs,
      x: input.x,
      y: input.y,
      width: input.width,
      height: input.height,
      data: input.data,
      preview: input.preview,
    },
    durationMs: input.durationMs,
    license: originalLicense,
    source: 'vibe-creator-original',
    sortOrder: input.sortOrder,
  };
}

/**
 * Built-in text presets served through the Video Studio asset catalog API.
 */
export const studioTextAssets: StudioAsset[] = [
  textAsset({
    id: 'opening',
    title: 'Hook Pembuka',
    description: 'Pembuka kuat untuk 3 detik pertama.',
    category: 'opening',
    tags: ['hook', 'intro', 'short'],
    sortOrder: 10,
    text: '3 HAL YANG WAJIB TAU',
    durationMs: 3000,
    x: 50,
    y: 22,
    width: 82,
    height: 16,
    data: {
      fontSize: 56,
      fontWeight: 'bold',
      fontStyle: 'normal',
      color: '#fff7ed',
      backgroundColor: 'rgba(234, 88, 12, 0.82)',
      textAlign: 'center',
      animation: 'slide-down',
    },
    preview: { variant: 'hook', badge: 'Intro', title: '3 HAL', subtitle: 'WAJIB TAU' },
  }),
  textAsset({
    id: 'opening-question',
    title: 'Pertanyaan Pembuka',
    description: 'Mulai video dengan pertanyaan yang bikin penasaran.',
    category: 'opening',
    tags: ['hook', 'question', 'retention'],
    sortOrder: 20,
    text: 'KAMU PERNAH MERASA BEGINI?',
    durationMs: 3000,
    x: 50,
    y: 28,
    width: 84,
    height: 14,
    data: {
      fontSize: 44,
      fontWeight: 'bold',
      fontStyle: 'normal',
      color: '#ffffff',
      backgroundColor: 'rgba(88, 28, 135, 0.78)',
      textAlign: 'center',
      animation: 'slide-down',
    },
    preview: { variant: 'hook', badge: 'Hook', title: 'PERNAH?', subtitle: 'Question opener' },
  }),
  textAsset({
    id: 'opening-breaking',
    title: 'Breaking Hook',
    description: 'Pembuka bergaya berita atau update penting.',
    category: 'opening',
    tags: ['news', 'hook', 'urgent'],
    sortOrder: 30,
    text: 'INI UPDATE PENTING',
    durationMs: 3000,
    x: 50,
    y: 18,
    width: 88,
    height: 14,
    data: {
      fontSize: 48,
      fontWeight: 'bold',
      fontStyle: 'normal',
      color: '#ffffff',
      backgroundColor: 'rgba(220, 38, 38, 0.86)',
      textAlign: 'center',
      animation: 'slide-down',
    },
    preview: { variant: 'hook', badge: 'News', title: 'UPDATE', subtitle: 'PENTING' },
  }),
  textAsset({
    id: 'caption',
    title: 'Caption Bar',
    description: 'Caption bawah yang mudah dibaca untuk short.',
    category: 'caption',
    tags: ['caption', 'subtitle', 'bar'],
    sortOrder: 110,
    text: 'Tulis caption di sini',
    durationMs: 5000,
    x: 50,
    y: 82,
    width: 86,
    height: 10,
    data: {
      fontSize: 38,
      fontWeight: 'bold',
      fontStyle: 'normal',
      color: '#ffffff',
      backgroundColor: 'rgba(15, 23, 42, 0.82)',
      textAlign: 'center',
      animation: 'slide-up',
    },
    preview: { variant: 'caption', badge: 'Caption', title: 'Caption', subtitle: 'Readable bar' },
  }),
  textAsset({
    id: 'caption-keyword',
    title: 'Keyword Caption',
    description: 'Caption pendek dengan gaya keyword punchy.',
    category: 'caption',
    tags: ['caption', 'keyword', 'short'],
    sortOrder: 120,
    text: 'INI KUNCINYA',
    durationMs: 4000,
    x: 50,
    y: 76,
    width: 70,
    height: 12,
    data: {
      fontSize: 46,
      fontWeight: 'bold',
      fontStyle: 'normal',
      color: '#0f172a',
      backgroundColor: '#facc15',
      textAlign: 'center',
      animation: 'slide-up',
    },
    preview: { variant: 'caption', badge: 'Keyword', title: 'KUNCI', subtitle: 'Punch word' },
  }),
  textAsset({
    id: 'lower-third',
    title: 'Lower Third',
    description: 'Label nama/topik di area bawah video.',
    category: 'title',
    tags: ['lower-third', 'label', 'name'],
    sortOrder: 210,
    text: 'Nama Pembicara',
    durationMs: 5000,
    x: 34,
    y: 78,
    width: 48,
    height: 11,
    data: {
      fontSize: 36,
      fontWeight: 'bold',
      fontStyle: 'normal',
      color: '#ffffff',
      backgroundColor: '#ff4b1f',
      textAlign: 'left',
      animation: 'slide-up',
    },
    preview: { variant: 'lower-third', badge: 'Lower', title: 'Nama', subtitle: 'Pembicara' },
  }),
  textAsset({
    id: 'quote',
    title: 'Quote Focus',
    description: 'Tampilan quote yang cocok untuk highlight kalimat.',
    category: 'quote',
    tags: ['quote', 'highlight', 'statement'],
    sortOrder: 310,
    text: '"Mulai sebelum siap."',
    durationMs: 5000,
    x: 50,
    y: 48,
    width: 78,
    height: 20,
    data: {
      fontSize: 48,
      fontWeight: 'bold',
      fontStyle: 'italic',
      color: '#f8fafc',
      backgroundColor: 'rgba(15, 23, 42, 0.78)',
      textAlign: 'center',
      animation: 'fade',
    },
    preview: { variant: 'quote', badge: 'Quote', title: 'Quote', subtitle: 'Statement' },
  }),
  textAsset({
    id: 'cta',
    title: 'CTA Simple',
    description: 'Ajakan aksi singkat untuk akhir video.',
    category: 'closing',
    tags: ['cta', 'closing', 'engagement'],
    sortOrder: 410,
    text: 'FOLLOW UNTUK PART 2',
    durationMs: 5000,
    x: 50,
    y: 70,
    width: 76,
    height: 13,
    data: {
      fontSize: 44,
      fontWeight: 'bold',
      fontStyle: 'normal',
      color: '#ffffff',
      backgroundColor: '#10b981',
      textAlign: 'center',
      animation: 'slide-up',
    },
    preview: { variant: 'cta', badge: 'CTA', title: 'Follow', subtitle: 'Next part' },
  }),
];
