import type { StudioAsset, StudioAudioFilePayload } from './video-studio.schemas';

const pixabayLicense: StudioAsset['license'] = {
  name: 'Pixabay Content License',
  sourceUrl: 'https://pixabay.com/service/license-summary/',
  attributionRequired: false,
  commercialUse: true,
};

interface AudioFileAssetInput {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly category: string;
  readonly tags: readonly string[];
  readonly sortOrder: number;
  readonly fileName: string;
  readonly durationMs: number;
  readonly sourceUrl: string;
}

function audioAsset(input: AudioFileAssetInput): StudioAsset {
  const payload: StudioAudioFilePayload = {
    kind: 'audio-file',
    fileName: `pixabay-meme/${input.fileName}`,
    mimeType: 'audio/mpeg',
    durationMs: input.durationMs,
  };

  return {
    id: input.id,
    kind: 'audio',
    title: input.title,
    description: input.description,
    category: input.category,
    tags: [...input.tags, 'pixabay'],
    thumbnailUrl: null,
    previewUrl: `/api/v1/video-studio/assets/${input.id}/preview`,
    payload,
    durationMs: input.durationMs,
    license: {
      ...pixabayLicense,
      sourceUrl: input.sourceUrl,
    },
    source: 'pixabay-sound-effects',
    sortOrder: input.sortOrder,
  };
}

/**
 * Curated meme/reaction SFX stored locally so preview/export never hotlink third-party audio.
 */
export const studioAudioAssets: StudioAsset[] = [
  audioAsset({
    id: 'meme-pop',
    title: 'Memeclick',
    description: 'Klik meme super pendek untuk punchline dan cut cepat.',
    category: 'meme',
    tags: ['meme', 'click', 'viral', 'punchline'],
    sortOrder: 1000,
    fileName: 'technology-memeclick-506437.mp3',
    durationMs: 392,
    sourceUrl: 'https://pixabay.com/sound-effects/technology-memeclick-506437/',
  }),
  audioAsset({
    id: 'meme-fah',
    title: 'Fah!',
    description: 'Reaction shout pendek untuk momen kaget atau absurd.',
    category: 'meme',
    tags: ['meme', 'reaction', 'fah', 'voice'],
    sortOrder: 1010,
    fileName: 'people-fah-469417.mp3',
    durationMs: 1750,
    sourceUrl: 'https://pixabay.com/sound-effects/people-fah-469417/',
  }),
  audioAsset({
    id: 'meme-sus',
    title: 'Sus Meme',
    description: 'Sound suspicious untuk ekspresi curiga atau twist komedi.',
    category: 'meme',
    tags: ['meme', 'sus', 'funny', 'reaction'],
    sortOrder: 1020,
    fileName: 'film-special-effects-sus-meme-sound-181271.mp3',
    durationMs: 2904,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-sus-meme-sound-181271/',
  }),
  audioAsset({
    id: 'meme-what',
    title: 'What!? Meme',
    description: 'Sting what untuk cut bingung, fail, atau komentar cepat.',
    category: 'meme',
    tags: ['meme', 'what', 'reaction', 'thud'],
    sortOrder: 1030,
    fileName: 'film-special-effects-what-meme-388653.mp3',
    durationMs: 3109,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-what-meme-388653/',
  }),
  audioAsset({
    id: 'meme-aa-reverb',
    title: 'AA Reverb',
    description: 'Scream reverb untuk reaction dramatis dan exaggerated.',
    category: 'meme',
    tags: ['meme', 'scream', 'reverb', 'reaction'],
    sortOrder: 1040,
    fileName: 'film-special-effects-aa-with-reverb-meme-381632.mp3',
    durationMs: 5277,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-aa-with-reverb-meme-381632/',
  }),
  audioAsset({
    id: 'meme-vine-boom',
    title: 'Vine Boom',
    description: 'Bass boom pendek untuk punchline, zoom muka, atau reveal absurd.',
    category: 'meme',
    tags: ['meme', 'vine boom', 'boom', 'punchline'],
    sortOrder: 1050,
    fileName: 'film-special-effects-vine-boom-392646.mp3',
    durationMs: 1306,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-vine-boom-392646/',
  }),
  audioAsset({
    id: 'meme-vine-boom-spam',
    title: 'Vine Boom Spam',
    description: 'Rangkaian boom untuk edit cepat, spam zoom, dan escalation joke.',
    category: 'meme',
    tags: ['meme', 'vine boom', 'spam', 'escalation'],
    sortOrder: 1060,
    fileName: 'film-special-effects-vine-boom-spam-sound-effect-205568.mp3',
    durationMs: 9600,
    sourceUrl:
      'https://pixabay.com/sound-effects/film-special-effects-vine-boom-spam-sound-effect-205568/',
  }),
  audioAsset({
    id: 'meme-rizz',
    title: 'Rizz Sting',
    description: 'Sting rizz/vine-style untuk pose, glow-up, atau awkward charm.',
    category: 'meme',
    tags: ['meme', 'rizz', 'vine', 'sting'],
    sortOrder: 1070,
    fileName: 'rizz-sound-effects-458250.mp3',
    durationMs: 5094,
    sourceUrl: 'https://pixabay.com/sound-effects/rizz-sound-effects-458250/',
  }),
  audioAsset({
    id: 'meme-airhorn',
    title: 'Airhorn',
    description: 'Airhorn klasik untuk hype, chaos, atau punchline yang sengaja lebay.',
    category: 'meme',
    tags: ['meme', 'airhorn', 'hype', 'chaos'],
    sortOrder: 1080,
    fileName: 'film-special-effects-air-horn-sound-effect-372453.mp3',
    durationMs: 1724,
    sourceUrl:
      'https://pixabay.com/sound-effects/film-special-effects-air-horn-sound-effect-372453/',
  }),
  audioAsset({
    id: 'meme-wowowow',
    title: 'WOWOWOW',
    description: 'Voice random panjang untuk escalation joke dan edit absurd.',
    category: 'meme',
    tags: ['meme', 'wow', 'voice', 'absurd'],
    sortOrder: 1082,
    fileName: 'people-wowowowowowowow-103214.mp3',
    durationMs: 11784,
    sourceUrl: 'https://pixabay.com/sound-effects/people-wowowowowowowow-103214/',
  }),
  audioAsset({
    id: 'meme-hello-there',
    title: 'Hello There',
    description: 'Greeting meme super pendek untuk opening, cutaway, atau awkward entrance.',
    category: 'meme',
    tags: ['meme', 'hello', 'voice', 'greeting'],
    sortOrder: 1084,
    fileName: 'people-quothello-therequot-158832.mp3',
    durationMs: 1358,
    sourceUrl: 'https://pixabay.com/sound-effects/people-quothello-therequot-158832/',
  }),
  audioAsset({
    id: 'meme-wait-minute',
    title: 'Wait A Minute',
    description: 'Voice reaction untuk momen curiga, plot twist, atau reveal lucu.',
    category: 'meme',
    tags: ['meme', 'wait', 'reaction', 'voice'],
    sortOrder: 1086,
    fileName: 'people-wait-a-minute-who-are-you-425166.mp3',
    durationMs: 3960,
    sourceUrl: 'https://pixabay.com/sound-effects/people-wait-a-minute-who-are-you-425166/',
  }),
  audioAsset({
    id: 'meme-omaga',
    title: 'Omaga',
    description: 'Voice meme pendek untuk reaction kaget dan cut komedi cepat.',
    category: 'meme',
    tags: ['meme', 'omaga', 'reaction', 'voice'],
    sortOrder: 1088,
    fileName: 'people-omaga-rturr-version-242813.mp3',
    durationMs: 2821,
    sourceUrl: 'https://pixabay.com/sound-effects/people-omaga-rturr-version-242813/',
  }),
  audioAsset({
    id: 'meme-goofy-horn',
    title: 'Goofy Horn',
    description: 'Horn konyol untuk joke visual, fail, dan reveal lucu.',
    category: 'funny',
    tags: ['meme', 'horn', 'goofy', 'funny'],
    sortOrder: 1100,
    fileName: 'film-special-effects-goofy-ahh-car-horn-200870.mp3',
    durationMs: 3056,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-goofy-ahh-car-horn-200870/',
  }),
  audioAsset({
    id: 'meme-fart-4',
    title: 'Fart 4',
    description: 'Meme fart singkat untuk punchline komedi slapstick.',
    category: 'funny',
    tags: ['meme', 'fart', 'funny', 'punchline'],
    sortOrder: 1110,
    fileName: 'film-efek-khusus-fart-4-228244.mp3',
    durationMs: 1881,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-fart-4-228244/',
  }),
  audioAsset({
    id: 'meme-fart-5',
    title: 'Fart 5',
    description: 'Variasi fart pendek untuk joke ringan.',
    category: 'funny',
    tags: ['meme', 'fart', 'funny', 'short'],
    sortOrder: 1120,
    fileName: 'film-efek-khusus-fart-5-228245.mp3',
    durationMs: 1881,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-fart-5-228245/',
  }),
  audioAsset({
    id: 'meme-fart-8',
    title: 'Fart 8',
    description: 'Fart super singkat untuk micro joke.',
    category: 'funny',
    tags: ['meme', 'fart', 'funny', 'micro'],
    sortOrder: 1130,
    fileName: 'film-efek-khusus-fart-8-228248.mp3',
    durationMs: 1228,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-fart-8-228248/',
  }),
  audioAsset({
    id: 'meme-hankie-pankie',
    title: 'Hankie Pankie',
    description: 'Voice meme playful untuk scene absurd atau awkward.',
    category: 'funny',
    tags: ['meme', 'voice', 'funny', 'awkward'],
    sortOrder: 1140,
    fileName: 'film-special-effects-hankie-pankie-222974.mp3',
    durationMs: 6744,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-hankie-pankie-222974/',
  }),
  audioAsset({
    id: 'funny-sad-trombone',
    title: 'Sad Trombone',
    description: 'Wah-wah fail klasik untuk joke gagal atau momen awkward.',
    category: 'funny',
    tags: ['meme', 'sad trombone', 'fail', 'awkward'],
    sortOrder: 1150,
    fileName: 'film-special-effects-wah-wah-sad-trombone-6347.mp3',
    durationMs: 5256,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-wah-wah-sad-trombone-6347/',
  }),
  audioAsset({
    id: 'funny-fail-trumpet',
    title: 'Fail Trumpet',
    description: 'Fail trumpet cepat untuk wrong answer, miss, dan flop.',
    category: 'funny',
    tags: ['meme', 'fail', 'trumpet', 'wrong'],
    sortOrder: 1160,
    fileName: 'film-special-effects-fail-trumpet-02-383962.mp3',
    durationMs: 1992,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-fail-trumpet-02-383962/',
  }),
  audioAsset({
    id: 'funny-fail',
    title: 'Fail Jingle',
    description: 'Fail cue komedi untuk punchline kalah, salah, atau gagal.',
    category: 'funny',
    tags: ['meme', 'fail', 'jingle', 'comedy'],
    sortOrder: 1170,
    fileName: 'film-special-effects-fail-144746.mp3',
    durationMs: 4049,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-fail-144746/',
  }),
  audioAsset({
    id: 'funny-surprise',
    title: 'Surprise Pop',
    description: 'Sting surprise pendek untuk reveal cepat dan jump cut lucu.',
    category: 'funny',
    tags: ['meme', 'surprise', 'pop', 'reveal'],
    sortOrder: 1180,
    fileName: 'film-special-effects-surprise-sound-effect-99300.mp3',
    durationMs: 1152,
    sourceUrl:
      'https://pixabay.com/sound-effects/film-special-effects-surprise-sound-effect-99300/',
  }),
  audioAsset({
    id: 'funny-comedy-flute',
    title: 'Comedy Flute',
    description: 'Flute komedi untuk awkward pause, stumble, dan reveal ringan.',
    category: 'funny',
    tags: ['meme', 'flute', 'comedy', 'awkward'],
    sortOrder: 1181,
    fileName: 'musical-comedy-flute-144564.mp3',
    durationMs: 16927,
    sourceUrl: 'https://pixabay.com/sound-effects/musical-comedy-flute-144564/',
  }),
  audioAsset({
    id: 'funny-cartoon-cry',
    title: 'Cartoon Cry',
    description: 'Cry cartoon pendek untuk fail kecil, drama lebay, dan punchline.',
    category: 'funny',
    tags: ['meme', 'cartoon', 'cry', 'reaction'],
    sortOrder: 1182,
    fileName: 'film-special-effects-funny-cartoon-cry-144756.mp3',
    durationMs: 1541,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-funny-cartoon-cry-144756/',
  }),
  audioAsset({
    id: 'funny-ooh',
    title: 'Ooh',
    description: 'Ooh reaction untuk punchline gagal, surprise kecil, dan comic timing.',
    category: 'funny',
    tags: ['meme', 'ooh', 'fail', 'reaction'],
    sortOrder: 1183,
    fileName: 'people-ooh-123103.mp3',
    durationMs: 1776,
    sourceUrl: 'https://pixabay.com/sound-effects/people-ooh-123103/',
  }),
  audioAsset({
    id: 'funny-pipe',
    title: 'Pipe',
    description: 'Pipe/cartoon sting untuk slapstick, silly cut, dan scene komedi.',
    category: 'funny',
    tags: ['meme', 'pipe', 'cartoon', 'slapstick'],
    sortOrder: 1184,
    fileName: 'film-special-effects-pipe-117724.mp3',
    durationMs: 4180,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-pipe-117724/',
  }),
  audioAsset({
    id: 'funny-sumo-crunch',
    title: 'Sumo Crunch',
    description: 'Crunch cartoon untuk hit lucu, stumble, dan reaction slapstick.',
    category: 'funny',
    tags: ['meme', 'crunch', 'cartoon', 'slapstick'],
    sortOrder: 1185,
    fileName: 'film-special-effects-funny-crunch-and-surprised-sumo-wrestler-145916.mp3',
    durationMs: 2194,
    sourceUrl:
      'https://pixabay.com/sound-effects/film-special-effects-funny-crunch-and-surprised-sumo-wrestler-145916/',
  }),
  audioAsset({
    id: 'funny-fart-flies',
    title: 'Fart & Flies',
    description: 'Fart comedy dengan texture flies untuk joke absurd dan gross-out ringan.',
    category: 'funny',
    tags: ['meme', 'fart', 'gross', 'funny'],
    sortOrder: 1186,
    fileName: 'film-special-effects-fart-flies-funny-152227.mp3',
    durationMs: 7680,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-fart-flies-funny-152227/',
  }),
  audioAsset({
    id: 'funny-brass',
    title: 'Brass Fanfare',
    description: 'Brass pendek untuk unexpected turn, reveal kecil, dan game-like punchline.',
    category: 'funny',
    tags: ['meme', 'brass', 'fanfare', 'reveal'],
    sortOrder: 1187,
    fileName: 'film-special-effects-brass-144755.mp3',
    durationMs: 4362,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-brass-144755/',
  }),
  audioAsset({
    id: 'funny-evil-witch-laugh',
    title: 'Evil Witch Laugh',
    description: 'Laugh jahat pendek untuk prank, twist, dan villain moment komedi.',
    category: 'funny',
    tags: ['meme', 'laugh', 'evil', 'twist'],
    sortOrder: 1188,
    fileName: 'horror-evil-witch-laugh-140135.mp3',
    durationMs: 3056,
    sourceUrl: 'https://pixabay.com/sound-effects/horror-evil-witch-laugh-140135/',
  }),
  audioAsset({
    id: 'reaction-bruh',
    title: 'Bruh',
    description: 'Reaction bruh singkat untuk momen kecewa, aneh, atau deadpan.',
    category: 'reaction',
    tags: ['reaction', 'bruh', 'meme', 'deadpan'],
    sortOrder: 1190,
    fileName: 'people-bruh-41009.mp3',
    durationMs: 1392,
    sourceUrl: 'https://pixabay.com/sound-effects/people-bruh-41009/',
  }),
  audioAsset({
    id: 'reaction-yeah-boy',
    title: 'Yeah Boy',
    description: 'Voice reaction positif untuk win, reveal, dan hype kecil.',
    category: 'reaction',
    tags: ['reaction', 'voice', 'yeah', 'meme'],
    sortOrder: 1200,
    fileName: 'people-yeah-boy-114748.mp3',
    durationMs: 1920,
    sourceUrl: 'https://pixabay.com/sound-effects/people-yeah-boy-114748/',
  }),
  audioAsset({
    id: 'reaction-i-got-this',
    title: 'I Got This!',
    description: 'Voice confidence untuk sebelum aksi atau setup komedi.',
    category: 'reaction',
    tags: ['reaction', 'voice', 'confidence', 'meme'],
    sortOrder: 1210,
    fileName: 'people-i-got-this-467997.mp3',
    durationMs: 1176,
    sourceUrl: 'https://pixabay.com/sound-effects/people-i-got-this-467997/',
  }),
  audioAsset({
    id: 'reaction-amazing',
    title: "Isn't That Amazing",
    description: 'Voice reaction singkat untuk reveal aneh atau lucu.',
    category: 'reaction',
    tags: ['reaction', 'voice', 'amazing', 'meme'],
    sortOrder: 1220,
    fileName: 'people-isnt-that-amazing-meme-sfx-172488.mp3',
    durationMs: 1384,
    sourceUrl: 'https://pixabay.com/sound-effects/people-isnt-that-amazing-meme-sfx-172488/',
  }),
  audioAsset({
    id: 'reaction-watch-yo-jet',
    title: 'Watch Yo Jet',
    description: 'Voice meme panjang untuk punchline dan reaction clip.',
    category: 'reaction',
    tags: ['reaction', 'voice', 'viral', 'meme'],
    sortOrder: 1230,
    fileName: 'people-watch-yo-jet-bro-446063.mp3',
    durationMs: 4728,
    sourceUrl: 'https://pixabay.com/sound-effects/people-watch-yo-jet-bro-446063/',
  }),
  audioAsset({
    id: 'reaction-woooooaah',
    title: 'Woooooaah!',
    description: 'Scream wow untuk surprise dan visual reveal.',
    category: 'reaction',
    tags: ['reaction', 'scream', 'wow', 'meme'],
    sortOrder: 1240,
    fileName: 'people-woooooaah-199849.mp3',
    durationMs: 2328,
    sourceUrl: 'https://pixabay.com/sound-effects/people-woooooaah-199849/',
  }),
  audioAsset({
    id: 'reaction-insane-scream',
    title: 'Insane Funny Scream',
    description: 'Scream lucu untuk cut chaos, gagal, atau overreaction.',
    category: 'reaction',
    tags: ['reaction', 'scream', 'funny', 'meme'],
    sortOrder: 1250,
    fileName: 'rakyat-insane-funny-scream-199845.mp3',
    durationMs: 2208,
    sourceUrl: 'https://pixabay.com/sound-effects/people-insane-funny-scream-199845/',
  }),
  audioAsset({
    id: 'reaction-laugh',
    title: 'Sinister Laugh',
    description: 'Laugh pendek untuk twist, prank, dan reveal jail.',
    category: 'reaction',
    tags: ['reaction', 'laugh', 'meme', 'funny'],
    sortOrder: 1260,
    fileName: 'horror-sinister-laugh-140131.mp3',
    durationMs: 3239,
    sourceUrl: 'https://pixabay.com/sound-effects/horror-sinister-laugh-140131/',
  }),
  audioAsset({
    id: 'reaction-hahaha',
    title: 'Hahaha',
    description: 'Laugh singkat untuk komentar lucu dan punchline ringan.',
    category: 'reaction',
    tags: ['reaction', 'laugh', 'happy', 'meme'],
    sortOrder: 1270,
    fileName: 'film-special-effects-hahaha-251796.mp3',
    durationMs: 1802,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-hahaha-251796/',
  }),
  audioAsset({
    id: 'reaction-meow-egg',
    title: 'Meow To An Egg',
    description: 'Audio absurd untuk meme random dan unexpected cut.',
    category: 'reaction',
    tags: ['reaction', 'meow', 'absurd', 'meme'],
    sortOrder: 1280,
    fileName: 'people-meow-to-an-egg-36412.mp3',
    durationMs: 9561,
    sourceUrl: 'https://pixabay.com/sound-effects/people-meow-to-an-egg-36412/',
  }),
  audioAsset({
    id: 'reaction-no-no-no',
    title: 'No No No',
    description: 'Voice panik untuk warning, mistake, atau setup fail.',
    category: 'reaction',
    tags: ['reaction', 'no no no', 'panic', 'fail'],
    sortOrder: 1290,
    fileName: 'people-no-no-no-242246.mp3',
    durationMs: 3432,
    sourceUrl: 'https://pixabay.com/sound-effects/people-no-no-no-242246/',
  }),
  audioAsset({
    id: 'reaction-oh-no',
    title: 'Oh No',
    description: 'Reaction oh-no untuk mistake, reveal buruk, atau cut komedi.',
    category: 'reaction',
    tags: ['reaction', 'oh no', 'mistake', 'meme'],
    sortOrder: 1295,
    fileName: 'people-oh-no-392258.mp3',
    durationMs: 2088,
    sourceUrl: 'https://pixabay.com/sound-effects/people-oh-no-392258/',
  }),
  audioAsset({
    id: 'reaction-my-good',
    title: 'My Good',
    description: 'Voice reaction pendek untuk moment lucu, manis, atau unexpected.',
    category: 'reaction',
    tags: ['reaction', 'voice', 'meme', 'funny'],
    sortOrder: 1296,
    fileName: 'people-my-good-120319.mp3',
    durationMs: 1959,
    sourceUrl: 'https://pixabay.com/sound-effects/people-my-good-120319/',
  }),
  audioAsset({
    id: 'reaction-funny-reaction',
    title: 'Funny Reaction',
    description: 'Reaction cue pendek untuk punchline, cutaway, dan edit viral.',
    category: 'reaction',
    tags: ['reaction', 'meme', 'funny', 'viral'],
    sortOrder: 1297,
    fileName: 'film-special-effects-funny-reaction-120318.mp3',
    durationMs: 2011,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-funny-reaction-120318/',
  }),
  audioAsset({
    id: 'reaction-dog-call',
    title: 'Dog Call',
    description: 'Call reaction pendek untuk cut random, pet meme, dan joke absurd.',
    category: 'reaction',
    tags: ['reaction', 'dog', 'call', 'meme'],
    sortOrder: 1298,
    fileName: 'people-woman-calling-dog-120316.mp3',
    durationMs: 1332,
    sourceUrl: 'https://pixabay.com/sound-effects/people-woman-calling-dog-120316/',
  }),
  audioAsset({
    id: 'reaction-oh-my-god',
    title: 'Oh My God',
    description: 'Voice OMG untuk surprise, shocked reaction, dan reveal cepat.',
    category: 'reaction',
    tags: ['reaction', 'omg', 'voice', 'meme'],
    sortOrder: 1299,
    fileName: 'people-oh-my-god-185142.mp3',
    durationMs: 2112,
    sourceUrl: 'https://pixabay.com/sound-effects/people-oh-my-god-185142/',
  }),
  audioAsset({
    id: 'reaction-man-scream',
    title: 'Man Scream',
    description: 'Scream pendek untuk shock cut, fail keras, dan overreaction.',
    category: 'reaction',
    tags: ['reaction', 'scream', 'shock', 'meme'],
    sortOrder: 1299,
    fileName: 'film-special-effects-man-scream-121085.mp3',
    durationMs: 3657,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-man-scream-121085/',
  }),
  audioAsset({
    id: 'impact-hit',
    title: 'Thud Hit',
    description: 'Dug/thud jelas untuk punchline, fail, dan cut keras.',
    category: 'impact',
    tags: ['impact', 'thud', 'dug', 'meme'],
    sortOrder: 1300,
    fileName: 'film-special-effects-thud-sound-effect-405470.mp3',
    durationMs: 3109,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-thud-sound-effect-405470/',
  }),
  audioAsset({
    id: 'impact-heavy-thud',
    title: 'Heavy Thud',
    description: 'Thud populer dengan hit lebih berat untuk dug, fall, dan emphasis.',
    category: 'impact',
    tags: ['impact', 'thud', 'boom', 'meme'],
    sortOrder: 1305,
    fileName: 'film-special-effects-thud-sound-effect-319090.mp3',
    durationMs: 3082,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-thud-sound-effect-319090/',
  }),
  audioAsset({
    id: 'impact-vine-cinematic-boom',
    title: 'Cinematic Boom',
    description: 'Boom cinematic untuk reveal besar, title drop, dan dramatic cut.',
    category: 'impact',
    tags: ['impact', 'boom', 'cinematic', 'vine boom'],
    sortOrder: 1310,
    fileName: 'film-special-effects-cinematic-boom-01-414572.mp3',
    durationMs: 2784,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-cinematic-boom-01-414572/',
  }),
  audioAsset({
    id: 'impact-knife-stab',
    title: 'Knife Stab',
    description: 'Sharp stab untuk quick cut, shock moment, dan dramatic emphasis.',
    category: 'impact',
    tags: ['impact', 'stab', 'shock', 'meme'],
    sortOrder: 1315,
    fileName: 'film-special-effects-knife-stab-121084.mp3',
    durationMs: 2534,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-knife-stab-121084/',
  }),
  audioAsset({
    id: 'suspense-waterphone',
    title: 'Waterphone',
    description: 'Sting tegang singkat untuk reveal misterius atau awkward.',
    category: 'suspense',
    tags: ['suspense', 'meme', 'tension', 'reveal'],
    sortOrder: 1400,
    fileName: 'film-special-effects-waterphone-174768.mp3',
    durationMs: 2880,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-waterphone-174768/',
  }),
  audioAsset({
    id: 'transition-record-scratch',
    title: 'Record Scratch',
    description: 'Stop/cut klasik untuk interrupt, plot twist, atau pause komedi.',
    category: 'transition',
    tags: ['transition', 'record scratch', 'stop', 'meme'],
    sortOrder: 1500,
    fileName: 'film-special-effects-record-scratch-108233.mp3',
    durationMs: 1656,
    sourceUrl: 'https://pixabay.com/sound-effects/film-special-effects-record-scratch-108233/',
  }),
  audioAsset({
    id: 'sfx-keyboard-typing',
    title: 'Keyboard Typing',
    description: 'Typing cepat untuk screen recording, coding, atau info edit.',
    category: 'sfx',
    tags: ['sfx', 'keyboard', 'typing', 'creator'],
    sortOrder: 1600,
    fileName: 'film-special-effects-keyboard-typing-sound-effect-335503.mp3',
    durationMs: 8098,
    sourceUrl:
      'https://pixabay.com/sound-effects/film-special-effects-keyboard-typing-sound-effect-335503/',
  }),
];
